---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib rescue
          ansible.builtin.get_url:
#            url: "https://packages.clickhouse.com/deb/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.deb"
            url: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse-common-static/clickhouse-common-static_22.3.3.44_amd64.deb"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.deb"

    - name: Install clickhouse packages
      become: true
#      ansible.builtin.yum:
      ansible.builtin.apt:
        name:
          - clickhouse-common-static-22.3.3.44.deb
          - clickhouse-client-{{ clickhouse_version }}.deb
          - clickhouse-server-{{ clickhouse_version }}.deb
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers

    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
