---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse

- name: Install vector
  hosts: vector
  roles:
    - vector-role

- name: Install lighthouse
  hosts: lighthouse

  pre_tasks:
    - name: Install nginx
      become: true
      ansible.builtin.dnf:
        name: nginx
        state: present
      notify: Start Nginx service

    - name: Install nodejs
      become: true
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: Устанавливаем git
      become: true
      ansible.builtin.dnf:
        name: git
        state: present
  roles:
    - lighthouse-role

