---
- name: Install Clickhouse
  hosts: clickhouse
  # Претаска отключает проверку ключа, в противном случай роль не проходит
  pre_tasks:
    - name: Отключение проверки gpg ключа
      delegate_to: localhost
      ansible.builtin.command: "{{ item }}"
      with_items:
        - "sed -i '2,10 s/^#*/#/' {{ playbook_dir }}/roles/clickhouse/tasks/install/dnf.yml"
        - "sed -i '20 s/^#*/#/' {{ playbook_dir }}/roles/clickhouse/tasks/install/dnf.yml"
        - "sed -i '36 s/^#*/#/' {{ playbook_dir }}/roles/clickhouse/tasks/install/dnf.yml"
        - "sed -i '36 a\\    disable_gpg_check: true' {{ playbook_dir }}/roles/clickhouse/tasks/install/dnf.yml"
  roles:
    - clickhouse

- name: Install vector
  hosts: vector
  roles:
    - vector-role

- name: Install lighthouse
  hosts: lighthouse

  pre_tasks:
    - name: Install nginx
      become: true
      ansible.builtin.dnf:
        name: nginx
        state: present
      notify: Start Nginx service

    - name: Install nodejs
      become: true
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: Устанавливаем git
      become: true
      ansible.builtin.dnf:
        name: git
        state: present
  roles:
    - lighthouse-role

