---
# tasks file for lighthouse-role
- name: Install nginx
  become: true
  ansible.builtin.dnf:
    name: nginx
    state: present
  notify: Start Nginx service

- name: Install nodejs
  become: true
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Устанавливаем git
  become: true
  ansible.builtin.dnf:
    name: git
    state: present

- name: Клонируем репозиторий с программой
  become: true
  ansible.builtin.git:
    repo: "{{ repo_lighthouse }}"
    dest: "{{ dest_lighthouse }}"
    single_branch: true
    version: master

- name: Настройка конфигурации из шаблона
  become: true
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: Start Nginx service