---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Узнаем версию установленной программы vector
      ansible.builtin.shell: vector --version | awk '{print $2}'
      register: version_vector

    - name: Debug version_vector
      debug:
        msg: "{{version_vector.stdout}}"

    - name: Выполняем проверку валидации конфигурационного файла
      ansible.builtin.shell: sudo -u vector vector validate >/dev/null ; echo $?
      register: validate_vector

    - name: Debug validate_vector
      debug:
        msg: "{{validate_vector}}"

    - name: Версия установленной программы vector
      ansible.builtin.assert:
        that:
          - version_vector.stdout == "0.49.0"
        success_msg: "Выполнена проверка установленной версии программы vector.
                      Установлена корректная версия!"
        fail_msg: "Ожидалась версия программы vector 0.49.0, но найдена {{ version_vector.stdout }}"

    - name: Проверка валидности конфигурационного файла
      ansible.builtin.assert:
        that:
            - validate_vector.stdout == "0"
        success_msg: "Конфигурационный файл без ошибок"
        fail_msg: "Ошибка при валидации конфигурационного файла"