apiVersion: v1
kind: Namespace
metadata:
  name:  app     # Имя вашего нового пространства имен
  labels:
    app: app
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /home/ubuntu/localVolume/front
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql
  namespace: app
spec:
  volumeName: pv-mysql
  storageClassName: ""
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: app
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app
  namespace: app
  labels:
    app: app
spec:
  replicas: 2 # Колличество подов
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: kolchinvladimir/app-animals:1.0.5
          ports:
            - containerPort: 80
              name: app
          env:
          - name: DB_HOST
            value: "mysql"
          - name: DB_USER
            value: "mysql"
          - name: DB_PASSWORD
            value: "mysql"
          - name: DB_NAME
            value: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: app
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "mysql"
            - name: MYSQL_USER
              value: "mysql"
            - name: MYSQL_PASSWORD
              value: "mysql"
            - name: MYSQL_DATABASE
              value: "mysql"
          volumeMounts:
            - name: storage
              mountPath: /var/lib/mysql
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: pvc-mysql
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
  namespace: app
spec:
  type: NodePort
  ports:
  - name: app
    port: 80
    targetPort: 80
    nodePort: 31100
  selector:
    app: app
