apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /home/ubuntu/localVolume/app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql
  namespace: app
spec:
  volumeName: pv-mysql
  storageClassName: ""
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: app
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app
  namespace: app
  labels:
    app: app
spec:
  replicas: 2 # Колличество подов
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: kolchinvladimir/app-animals:1.0.5
          ports:
            - containerPort: 80
              name: app
          env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: DB_NAME
      imagePullSecrets:
        - name: yc-registry-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: app
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: DB_NAME
          volumeMounts:
            - name: storage
              mountPath: /var/lib/mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: pvc-mysql
        - name: init-sql
          configMap:
            name: mysql-init-sql
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
  namespace: app
spec:
  type: NodePort
  ports:
  - name: app
    port: 80
    targetPort: 80
    nodePort: 31100
  selector:
    app: app
