apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app
  namespace: app
  labels:
    app: app
spec:
  replicas: 2 # Колличество подов
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: kolchinvladimir/app-animals:1.0.5
          ports:
            - containerPort: 80
              name: app
          env:
          - name: DB_HOST
            value: "mysql"
          - name: DB_USER
            value: "mysql"
          - name: DB_PASSWORD
            value: "mysql"
          - name: DB_NAME
            value: "mysql"
      imagePullSecrets:
        - name: yc-registry-secret

