# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: DB_HOST
    envs:
      - .env

#secretGenerator:
#  - name: my-secret
#    envs:
#      - .env
