apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
  namespace: app
spec:
  type: NodePort
  ports:
  - name: app
    port: 80
    targetPort: 80
    nodePort: 31100
  selector:
    app: app
