##cloud-config
#users:
#  - name: ubuntu
#    groups: sudo
#    shell: /bin/bash
#    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
#    ssh_authorized_keys:
#      - ${ssh_public_key}
#package_update: true
#package_upgrade: false
#
#packages: ${packages}
#
## Копирование конфигурационного файла nginx (обратный прокси). Используем кодировку для передачи файла, т.к. даные содержат спец символы в виде :, а он корректно не передается
#write_files:
#  - path: /home/ubuntu/addons.yml
#    permissions: '0644'
#    encoding: b64
#    content: ${file_addons}