#cloud-config
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${ssh_public_key}
package_update: true
package_upgrade: false

packages: ${packages}

write_files:
  # Копирование конфигурационного файла nginx (обратный прокси). Используем кодировку для передачи файла, т.к. даные содержат спец символы в виде :, а он корректно не передается
  - path: /tmp/proxy
    permissions: '0644'
    encoding: b64
    content: ${base64encode(file_content)}

  # Файл с хостами для запуска плейбука установки кластера k8s
  - path: /tmp/hosts.ini
    permissions: '0644'
    encoding: b64
    content: ${base64encode(file_ansible_hosts)}

  # Приватный клюя для VM БАСТИОН
  - path: /tmp/id_rsa
    permissions: '0600'
    encoding: b64
    content: ${base64encode(ssh_private_key)}

  # Файл с настройками кластера
  - path: /tmp/addons.yml
    permissions: '0644'
    encoding: b64
    content: ${file_addons}

  # Скрипт установки кластера k8s
  - path: /tmp/kubespray.sh
    permissions: '0777'
    encoding: b64
    content: ${file_kubespray}

  # Скрипт установки grafana
  - path: /tmp/kube-prometheus.sh
    permissions: '0777'
    encoding: b64
    content: ${file_prometheus}

  # Файл включения node port для графана
  - path: /tmp/grafana-node-port.yml
    permissions: '0644'
    encoding: b64
    content: ${file_grafana_node_port}

  # Общий файл yml с проектом
  - path: /home/ubuntu/app.yml
    permissions: '0644'
    encoding: b64
    content: ${file_app}

  # База данных для проекта
  - path: /home/ubuntu/animals.sql
    permissions: '0644'
    encoding: b64
    content: ${file_base}

  # Скрипт установки приложения
  - path: /home/ubuntu/app.sh
    permissions: '0777'
    encoding: b64
    content: ${file_appsh}

  # Шаблон создания секрета
  - path: /home/ubuntu/mysqlsecret.yaml.tmpl
    permissions: '0644'
    encoding: b64
    content: ${file_secret_tmpl}

  # Скрипт установки сервиса atlantis
  - path: /home/ubuntu/atlantis-install.sh
    permissions: '0777'
    encoding: b64
    content: ${file_atlantis}

  # Файл yandex_auth
  - path: /home/ubuntu/authorized-key-diplom.json
    permissions: '0600'
    encoding: b64
    content: ${file_yandex_auth}

  # Файл auth_key_s3
  - path: /home/ubuntu/credentials-diplom
    permissions: '0600'
    encoding: b64
    content: ${file_auth_key_s3}

  # Файл ssh_public_key
  - path: /home/ubuntu/id_rsa.pub
    permissions: '0600'
    encoding: b64
    content: ${file_ssh_public_key}

  # Файл terraformrc
  - path: /home/ubuntu/.terraformrc
    permissions: '0644'
    encoding: b64
    content: ${file_terraformrc}

  # Скрипт установки соединения с gitlab
  - path: /home/ubuntu/connect.sh
    permissions: '0777'
    encoding: b64
    content: ${file_connect}

  # Закрытый ключ сертификата
  - path: /etc/nginx/privkey.pem
    permissions: '0600'
    encoding: b64
    content: ${file_privkey}

  # Закрытый ключ сертификата
  - path: /etc/nginx/fullchain.pem
    permissions: '0600'
    encoding: b64
    content: ${file_fullchain}

  # Закрытый ключ сертификата
  - path: /etc/nginx/chain.pem
    permissions: '0600'
    encoding: b64
    content: ${file_chain}

runcmd:
  - echo "Запуск cloud init"
  - echo "Изменяем владельца домашнего каталога пользователя UBUNTU "
  - sudo chown -R ubuntu:ubuntu /home/ubuntu
  - echo "Копируем файл .bashrc"
  - sudo -u ubuntu cp /etc/skel/.bashrc /etc/skel/.profile /home/ubuntu
  - echo "Копируем приватный ключ (который создали с помощью terraform) для бастион в каталог пользователя UBUNTU "
  - sudo cp /tmp/id_rsa /home/ubuntu/.ssh/id_rsa; sudo chown ubuntu:ubuntu /home/ubuntu/.ssh/id_rsa
  - echo "Копируем конфигурационный файл nginx "
  - sudo cp /tmp/proxy /etc/nginx/sites-available/proxy
  - sudo ln -s /etc/nginx/sites-available/proxy /etc/nginx/sites-enabled/proxy

  - echo "Выполняем настройку container registry"
  - usermod -aG docker ubuntu
  # Загружаем свой подготовленный образ чтоб в дальнейшем не загружать его в ручную в yandex registry
  - docker pull kolchinvladimir/app-animals:1.0.5
  # Переименовываем образ для yandex registry
  - docker tag kolchinvladimir/app-animals:1.0.5 cr.yandex/${yandex_container_registry_id}/app-animals:1.0.5
  # Авторизовываемся в yandex container registry
  - cat /home/ubuntu/authorized-key-diplom.json | docker login --username json_key --password-stdin cr.yandex
  # Загружаем образ в yandex registry чтоб руками не пушить
  - docker push cr.yandex/${yandex_container_registry_id}/app-animals:1.0.5
  # Удаляем образа после загрузки в yandex cloud registry для чистоты эксперимента
  - docker rmi cr.yandex/crpue89b167dfch3bcs8/app-animals:1.0.5
  - docker rmi kolchinvladimir/app-animals:1.0.5

  - echo "Выполняем установку кластера k8s"
  - [ sudo, -u, ubuntu, -i, bash, -c, "/tmp/kubespray.sh ${name_control_node}" ]

  - echo "Выполняем установку prometheus grafana"
  - [ sudo, -u, ubuntu, -i, bash, -c, "/tmp/kube-prometheus.sh" ]

  - echo "Выполняем деплой тестового приложения"
  - [ sudo, -u, ubuntu, -i, bash, -c, "db_host=${db_host} db_user=${db_user} db_password=${db_password} db_name=${db_name} mysql_root_password=${mysql_root_password} /home/ubuntu/app.sh" ]

  - echo "Выполняем деплой сервиса atlantis"
  - [ sudo, -u, ubuntu, -i, bash, -c, "SECRET=${secret} TOKEN=${token} URL=${url} USERNAME=${username} REPO_ALLOWLIST=${repo_github} YC_CLOUD_ID=${yc_cloud_id} YC_FOLDER_ID=${yc_folder_id} DB_HOST=${db_host} DB_USER=${db_user} DB_PASSWORD=${db_password} DB_NAME=${db_name} MYSQL_ROOT_PASSWORD=${mysql_root_password} TOKEN_GITLAB_AGENT=${token_gitlab_agent} TOKEN_GITLAB_RUNNER=${token_gitlab_runner} FILE_PRIVKEY=${file_privkey} FILE_FULLCHAIN=${file_fullchain} FILE_CHAIN=${file_chain} /home/ubuntu/atlantis-install.sh" ]

  - echo "Выполняем подключение к gitlab репозиторию"
  - [ sudo, -u, ubuntu, -i, bash, -c, "TOKEN_GITLAB_AGENT=${token_gitlab_agent} TOKEN_GITLAB_RUNNER=${token_gitlab_runner} /home/ubuntu/connect.sh" ]
