#cloud-config
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${ssh_public_key}
package_update: true
package_upgrade: false

packages: ${packages}

write_files:
  # Копирование конфигурационного файла nginx (обратный прокси). Используем кодировку для передачи файла, т.к. даные содержат спец символы в виде :, а он корректно не передается
  - path: /tmp/proxy
    permissions: '0644'
    encoding: b64
    content: ${base64encode(file_content)}

  # Файл с хостами для запуска плейбука установки кластера k8s
  - path: /tmp/hosts.ini
    permissions: '0644'
    encoding: b64
    content: ${base64encode(file_ansible_hosts)}

  # Приватный клюя для VM БАСТИОН
  - path: /tmp/id_rsa
    permissions: '0600'
    encoding: b64
    content: ${base64encode(ssh_private_key)}

  # Файл с настройками кластера
  - path: /tmp/addons.yml
    permissions: '0644'
    encoding: b64
    content: ${file_addons}

  # Скрипт установки кластера k8s
  - path: /tmp/kubespray.sh
    permissions: '0777'
    encoding: b64
    content: ${file_kubespray}

  # Скрипт установки grafana
  - path: /tmp/kube-prometheus.sh
    permissions: '0777'
    encoding: b64
    content: ${file_prometheus}

  # Файл включения node port для графана
  - path: /tmp/grafana-node-port.yml
    permissions: '0644'
    encoding: b64
    content: ${file_grafana_node_port}

  # Общий файл yml с проектом
  - path: /home/ubuntu/app.yml
    permissions: '0644'
    encoding: b64
    content: ${file_app}

  # База данных для проекта
  - path: /home/ubuntu/animals.sql
    permissions: '0644'
    encoding: b64
    content: ${file_base}

  # Скрипт установки приложения
  - path: /home/ubuntu/app.sh
    permissions: '0777'
    encoding: b64
    content: ${file_appsh}

runcmd:
  - echo "Запуск cloud init"
  - echo "Изменяем владельца домашнего каталога пользователя UBUNTU "
  - sudo chown -R ubuntu:ubuntu /home/ubuntu
  - echo "Копируем файл .bashrc"
  - sudo -u ubuntu cp /etc/skel/.bashrc /etc/skel/.profile /home/ubuntu
  - echo "Копируем приватный ключ (который создали с помощью terraform) для бастион в каталог пользователя UBUNTU "
  - sudo cp /tmp/id_rsa /home/ubuntu/.ssh/id_rsa; sudo chown ubuntu:ubuntu /home/ubuntu/.ssh/id_rsa
  - echo "Копируем конфигурационный файл nginx "
  - sudo cp /tmp/proxy /etc/nginx/sites-available/proxy
  - sudo ln -s /etc/nginx/sites-available/proxy /etc/nginx/sites-enabled/proxy
  - echo "Выполняем установку кластера k8s"
  - [ sudo, -u, ubuntu, -i, bash, -c, "/tmp/kubespray.sh ${name_control_node}" ]
#  - echo "Выполняем установку prometheus grafana"
#  - [ sudo, -u, ubuntu, -i, bash, -c, "/tmp/kube-prometheus.sh" ]
#  - echo "Выполняем деплой тестового приложения"
#  - [ sudo, -u, ubuntu, -i, bash, -c, "/home/ubuntu/app.sh" ]
