---
group_control:
  hosts:
    control-node:
      ansible_host: 158.160.51.197
      ansible_user: ubuntu
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
group_managed:
  hosts:
    managed-node1:
      ansible_host: 51.250.14.226
      ansible_user: ubuntu
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    managed-node2:
      ansible_host: 51.250.1.142
      ansible_user: ubuntu
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
